### ISSUE TITLE
Release docker image to docker hub

### ISSUE THREAD

**Issue by dgroup** [dgroup/g2w#2]
- https://github.com/marketplace/actions/build-and-push-docker-images
- https://github.com/docker/build-push-action

**Comment by 0pdd** [comment]
@dgroup the puzzle [#45](https://github.com/dgroup/g2w/issues/45) is still not solved.

**Comment by 0pdd** [comment]
@dgroup the only puzzle [#45](https://github.com/dgroup/g2w/issues/45) is solved here.
